export const v2_DEFAULT_STYLE_SECTION_BOILERPLATES: Partial<
  Record<string, Record<string, string | number>>
> = {
  grid: {
    layoutMode: "grid3x3",
    flex42ThreeRow: "bottom",
    flex42Align: "center",
    left: 32,
    top: 96,
    rowGap: 8,
    columnGap: 20,
    columns: 3,
  },
  weekFlag: {
    top: 564,
    left: 1556,
    width: 580,
    height: 120,
    fontSize: 76,
    fontWeight: 700,
  },
  topObjectContainer: {
    position: "absolute",
    width: 4000,
    height: 2250,
    zIndex: 30,
  },
  profileImage: {
    top: 516,
    left: 2400,
    width: 1540,
    height: 1540,
    zIndex: 10,
  },
  profileFrame: {
    position: "absolute",
    width: 4000,
    height: 2250,
    zIndex: 20,
  },
  profileTextRootStyle: {
    left: 4,
    zIndex: 30,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  profileTextWrapperStyle: {
    position: "absolute",
    width: 1318,
    height: 160,
    bottom: 268,
    right: 200,
    rotate: "1.6deg",
  },
  profileTextStyle: {
    lineHeight: 1,
    fontWeight: 900,
    textAlign: "center",
  },
  profileTextArtistImageStyle: {
    display: "block",
  },
  cardStreamingDay: {
    top: 0,
    left: 0,
    width: 160,
    height: 100,
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingLeft: 8,
  },
  cardStreamingDate: {
    width: 160,
    height: 100,
    position: "absolute",
    top: -16,
    left: -24,
    zIndex: 10,
  },
  cardStreamingTime: {
    width: 252,
    height: 40,
    top: 508,
  },
  cardMainTitleContainer: {
    height: 280,
    top: 132,
  },
  cardSubTitleContainer: {
    height: 64,
    top: 440,
  },
  cardContainer: {
    width: 600,
    height: 504,
    top: 68,
    left: 10,
  },
  streamingDayStyle: {
    fontSize: 56,
    fontWeight: 700,
    lineHeight: 1,
    textAlign: "left",
  },
  streamingDateStyle: {
    fontSize: 68,
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: 3,
    rotate: "-14deg",
    textAlign: "center",
  },
  streamingTimeStyle: {
    fontSize: 31,
    fontWeight: 400,
    lineHeight: 1,
    textAlign: "center",
  },
  mainTitleWrapperStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  subTitleWrapperStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  mainTitleTextStyle: {
    lineHeight: 1.2,
    fontWeight: 700,
    textAlign: "center",
  },
  subTitleTextStyle: {
    lineHeight: 1,
    fontWeight: 400,
    textAlign: "center",
  },
};
