export const v2_DEFAULT_STYLE_SECTION_BOILERPLATES: Partial<
  Record<string, Record<string, string | number>>
> = {
  grid: {
    layoutMode: "grid3x3",
    flex42ThreeRow: "bottom",
    flex42Align: "center",
    left: 33,
    top: 121,
    rowGap: 68,
    columnGap: 20,
    columns: 3,
    width: 2201,
    height: 1816,
    gridEmptySlotA: 3,
    gridEmptySlotB: 6,
  },
  weekFlag: {
    top: 568,
    left: 1557,
    width: 580,
    height: 114,
    fontSize: 76,
    fontWeight: 700,
    lineHeight: 1,
  },
  weekDates: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 4000,
    height: 2250,
  },
  weekDatesStart: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 200,
    height: 200,
  },
  weekDatesEnd: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 200,
    height: 200,
  },
  weekStartMonth: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 200,
    height: 90,
    fontSize: 90,
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: 0,
    textAlign: "center",
  },
  weekStartDate: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 200,
    height: 200,
    fontSize: 200,
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: 0,
    textAlign: "center",
  },
  weekEndMonth: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 200,
    height: 90,
    fontSize: 90,
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: 0,
    textAlign: "center",
  },
  weekEndDate: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 200,
    height: 200,
    fontSize: 200,
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: 0,
    textAlign: "center",
  },
  topObjectContainer: {
    position: "absolute",
    width: 4000,
    height: 2250,
    zIndex: 50,
  },
  memoContainer: {
    position: "absolute",
    left: 1513,
    top: 749,
    width: 720,
    height: 560,
    zIndex: 60,
  },
  memoContentContainer: {
    position: "absolute",
    left: 1513,
    top: 749,
    width: 720,
    height: 560,
  },
  memoTextContainer: {
    position: "absolute",
    left: 100,
    top: 160,
    width: 520,
    height: 300,
  },
  memoTextStyle: {
    color: "#EC6F62",
    fontFamily: "Escoredream",
    fontSize: 56,
    fontWeight: 600,
    lineHeight: 1,
    textAlign: "center",
  },
  profileImage: {
    top: 496,
    left: 2400,
    width: 1540,
    height: 1540,
    zIndex: 20,
  },
  profileFrame: {
    position: "absolute",
    width: 4000,
    height: 2250,
    zIndex: 10,
  },
  artistTextRootStyle: {
    position: "absolute",
    left: 2630,
    top: 1820,
    width: 1000,
    height: 120,
    zIndex: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  artistTextWrapperStyle: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 1000,
    height: 120,
    rotateDeg: 1.8,
  },
  artistTextStyle: {
    fontSize: 76,
    lineHeight: 1,
    fontWeight: 700,
    textAlign: "center",
  },
  artistObjectStyle: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 4000,
    height: 2250,
  },
  cardStreamingDay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 0,
    height: 0,
    opacity: 0,
    pointerEvents: "none",
  },
  cardStreamingDate: {
    width: 160,
    height: 100,
    position: "absolute",
    top: 3,
    left: 31,
    zIndex: 10,
  },
  cardStreamingTime: {
    width: 540,
    height: 40,
    left: 98,
    top: 476,
  },
  cardMainTitleContainer: {
    width: 540,
    height: 240,
    left: 98,
    top: 123,
  },
  cardSubTitleContainer: {
    width: 540,
    height: 76,
    left: 98,
    top: 404,
  },
  cardContainer: {
    width: 720,
    height: 560,
    top: 0,
    left: 0,
  },
  streamingDayStyle: {
    fontSize: 1,
    fontWeight: 400,
    lineHeight: 1,
    opacity: 0,
    textAlign: "left",
  },
  streamingDateStyle: {
    fontSize: 68,
    fontWeight: 400,
    lineHeight: 1,
    letterSpacing: 0,
    textAlign: "center",
  },
  streamingTimeStyle: {
    fontSize: 32,
    fontWeight: 400,
    lineHeight: 1,
    textAlign: "center",
  },
  mainTitleWrapperStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  subTitleWrapperStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  mainTitleTextStyle: {
    fontSize: 82,
    lineHeight: 1,
    fontWeight: 700,
    textAlign: "center",
  },
  subTitleTextStyle: {
    fontSize: 58,
    lineHeight: 1,
    fontWeight: 400,
    letterSpacing: -1.16,
    textAlign: "center",
  },
};
